spring:

  datasource: # Configura o datasource do banco de dados.
    driver-class-name: org.postgresql.Driver # Especifica o driver JDBC (neste caso, para Postgres).
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:accounting} # Define a URL de conexão ao banco.
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari: # Configurações do HikariCP, o pool de conexões padrão do Spring Boot.
      pool-name: poll_accounting # Nome do pool, útil para logs e diagnósticos.
      maxLifetime: 600000 # Tempo máximo de vida de uma conexão no pool.
      connection-timeout: 60000 # Tempo máximo para obter uma conexão antes de gerar erro.
      idle-timeout: 600000 # Tempo de inatividade antes de uma conexão ser removida.
      minimum-idle: 2 # Número mínimo de conexões inativas que o pool deve manter.
      maximum-pool-size: 4 # Número máximo de conexões simultâneas.

  flyway: # Opcional
    enabled: true
    locations: classpath:db/migration,classpath:db/dev

  jpa: # Configura o JPA/Hibernate.
    database: POSTGRESQL # Especifica o banco usado.
    hibernate:
      ddl-auto: none # Define como o Hibernate gerencia o esquema do banco (usar none em produção).
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Define a estratégia de nomeação de tabelas/colunas.
    properties:
      hibernate: # Configurações avançadas do Hibernate.
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
        format_sql: true # Formata as queries SQL para facilitar leitura.
        use_sql_comments: true # Adiciona comentários nas queries geradas.
        connection: # Define o nível de isolamento de transação.
          isolation: 2 # 2 é READ_COMMITTED
        cache:
          use_second_level_cache: false # Habilita cache de segundo nível
          use_query_cache: false # Habilita cache de query.
        type:
          enumType:
            type: pgsql_enum # Personalização para usar enums
        jdbc:
          log:
            non_contextual_creation: true # Ajuda a rastrear conexões criadas fora do contexto transacional (pode desligar em produção).
    open-in-view: false #  Define se o Hibernate deve manter a sessão aberta durante a renderização da view. O false é recomendado para evitar problemas de performance e lazy loading.
    #    generate-ddl: true
    show-sql: true

  logging: # Configura o nível de log para queries SQL.
    level:
      org.hibernate.SQL: DEBUG # Loga queries executadas (usar INFO em produção).
      org.hibernate.type.descriptor.sql: TRACE  # Loga parâmetros das queries para depuração (usar WARN em produção).

management: # Define ajustes para o Spring Boot Actuator, um módulo que fornece endpoints prontos para monitorar, gerenciar e obter métricas da aplicação.
  endpoints:
    web:
      exposure:
        include: "*" # Essa configuração controla quais endpoints do Actuator estarão disponíveis via HTTP. Atenção: Expor todos os endpoints pode ser um risco de segurança, especialmente em ambientes de produção. Recomenda-se restringir os endpoints expostos.
  metrics:
    tags:
      application: ${spring.application.name} # Faz o micrometer organizar as métricas unificadas por nome de microsserviço
      environment: ${spring.profiles.active} # Organize tags para ambientes: Inclua informações úteis como ambiente (dev, prod) nas tags.

