server: # Define a porta em que o servidor embutido (por padrão, o Tomcat) irá escutar.
  port: ${SERVER_PORT:9203}

spring:

  application: # Define o nome da aplicação. Útil para identificação em logs e sistemas de monitoramento.
    name: accounting_investments

  profiles:
    active: dev

