apiVersion: 1

deleteDatasources: # Deleta todas as fontes de dados com possíveis nomes Prometheus e Loki
  - name: Prometheus
  - name: Loki

datasources: # Cria fontes de dados com os nomes Prometheus e Loki
  - name: Prometheus
    type: prometheus
    uid: prometheus # Identificador dessa fonte de dados
    url: http://prometheus:9090 # URL onde será iniciado - mesma porta usada no docker-compose.yml
    access: proxy
    orgId: 1
    basicAuth: false # Desativar autenticação
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    editable: true
    url: http://gateway:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\\[.+,(.+),.+\\]"
          name: TraceID
          url: '$${__value.raw}'
    secureJsonData:
      httpHeaderValue1: "tenant1"

