spring:

management: # Define ajustes para o Spring Boot Actuator, um módulo que fornece endpoints prontos para monitorar, gerenciar e obter métricas da aplicação.
  endpoints:
    web:
      exposure:
        include: info, metrics, health # Essa configuração controla quais endpoints do Actuator estarão disponíveis via HTTP. Atenção: Expor todos os endpoints pode ser um risco de segurança, especialmente em ambientes de produção. Recomenda-se restringir os endpoints expostos.
  endpoint:
    health:
      enabled: true
      show-details: always # Ele exibe informações detalhadas como o estado de bancos de dados, serviços externos, etc. Pode ter os valores: always (mostra detalhes sempre), when-authorized (detalhes apenas para usuários autenticados) e never (nunca mostra detalhes).
#  security:
#    enabled: true # Proteja endpoints sensíveis com autenticação
  health:
    circuit-breakers:
      enabled: true # Habilita verificações de saúde específicas para circuit breakers (caso esteja usando bibliotecas como Resilience4j ou Hystrix). O estado do circuito (fechado, aberto ou semi-aberto) será incluído no relatório de saúde.
  metrics:
    tags:
      application: ${spring.application.name} # Faz o micrometer organizar as métricas unificadas por nome de microsserviço
      environment: ${spring.profiles.active} # Organize tags para ambientes: Inclua informações úteis como ambiente (dev, prod) nas tags.

# endpoints.web.exposure.include: info, metrics, health
#  Define quais endpoints de gerenciamento serão expostos via web.
#
#  info: Exibe informações sobre a aplicação, como nome, versão, etc.
#  metrics: Exibe métricas da aplicação, como memória, uso de CPU, número de requisições, etc.
#  health: Exibe o estado de saúde da aplicação, como se está funcionando corretamente ou se há problemas com serviços dependentes.





